site_name: Clan Aggressor LATAM | Biblioteca de conocimientos
site_url: https://agulepe.github.io/aggressor/
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js
  - assets/js/init-glightbox.js
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sYUM6NQ4yN
      name: Call Aggressor en Discord
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ClanAgrressorArmaIII
      name: Call Aggressor en Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/clan.aggressor/
      name: Call Aggressor en Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ClanAggressor-vn4db
      name: Call Aggressor en Youtube
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@clan.aggressor
      name: Call Aggressor en Tiktok
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/CLANAGGRESSOR
      name: Call Aggressor en Steam
  generator: false
theme:
  language: es
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: red
  logo: assets/logo-aggressor.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - navigation.indexes
    - toc.follow
  plugins:
    - search
    - tags
    - typeset
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: true
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
copyright: Recopilación elaborada por Clan Aggressor LATAM &copy; 2019 - 2025
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - INTRO: index.md
  - TTP:
      - Tácticas, Técnicas y Procedimientos: ttp/index.md
      - Tirador designado:  ttp/tirador-designado.md
      - Médico de combate: ttp/medico-de-combate.md
  - DRILLS:
      - Drills de combate: drills/index.md
      - 1A | Ataque de escuadra: drills/ataque-escuadra.md
  - TLP:
      - Troop Leading Procedures: tlp/index.md
